name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u stesiam --password-stdin

    - name: Build the Docker image
      run: docker build . -f Dockerfile -t stesiam/luaposter-libertinus:latest

    - name: Push the Docker image
      run: docker push stesiam/luaposter-libertinus:latest
