name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u stesiam --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_NAME=stesiam/luaposter-libertinus
        TAG=$(date +%Y%m%d%H%M%S)
        docker build . -f Dockerfile -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest
    - name: Push the Docker image
      run: |
        IMAGE_NAME=stesiam/luaposter-libertinus
        TAG=$(date +%Y%m%d%H%M%S)
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest
